
---
- hosts: RouterFremont, RouterSFO
  connection: local
  gather_facts: no

  vars:
    cli:
       host: "{{ ansible_host }}"
       username: "cisco"
       password: "cisco"

  tasks:
  - vars:
       as_number: 7922
       remote_interface: GigabitEthernet0/0/0/2
       remote_neighbor: 2.2.2.2
#    template:
#       src: example4.j2
#       dest: "/tmp/ex4-{{ ansible_host }}.cfg"
    iosxr_config:
        provider: "{{ cli }}"
        src: example4.j2 
    when: 
       inventory_hostname == groups['RouterFremont'][0]
  - vars:
       as_number: 7922
       remote_interface: GigabitEthernet0/0/0/2
       remote_neighbor: 1.1.1.1
#    template:
#       src: example4.j2
#       dest: "/tmp/ex4-{{ ansible_host }}.cfg"
    iosxr_config:
       provider: "{{ cli }}"
       src: example4.j2
    when:
       inventory_hostname == groups['RouterSFO'][0]

