---
  - name: Configure L3 VPN Global parameters (dry-run)
    template:
       src: xr_l3vpn_interface_config.j2
       dest: "/tmp/l3vpn-{{ item.router }}-interface.cfg"
    when:
       dry_run 
  - name: Configure L3 VPN Global parameters
    iosxr_config:
        provider: "{{ cli }}"
        src: xr_l3vpn_interface_config.j2
    when:
       not dry_run
