- name: Global L3 VPN config
  include_role:
    name: l3vpn-global
  with_items:
    - "{{ l3vpn.sites }}"
- name: Interface L3 VPN config
  include_role:
    name: l3vpn-interface
  with_items:
    - "{{ l3vpn.sites }}"
